import type { SanityAsset } from '@sanity/image-url/lib/types/types';
export interface Post {
	_createdAt: string;
	_id: string;
	_rev: string;
	_type: 'post';
	_updatedAt: string;
	body: Body[];
	categories: Category[];
	excerpt: string;
	mainImage: MainImage;
	publishedAt: string;
	slug: Slug;
	title: string;
}

export interface Body {
	_key: string;
	_type: string;
	children: Child[];
	markDefs: any[];
	style: string;
}

export interface Child {
	_key: string;
	_type: string;
	marks: any[];
	text: string;
}

export interface Category {
	_key: string;
	_ref: string;
	_type: string;
}

export interface Image {
	_type: string;
	asset: SanityAsset;
}

export interface Slug {
	_type: string;
	current: string;
}

export interface Icon {
	_createdAt?: string;
	_id?: string;
	_rev?: string;
	_type: string;
	_updatedAt?: string;
	size: number;
	svg: string;
	title: string;
}

// Generated by https://quicktype.io

export interface SanityPage {
	_type: 'page';
	metaDescription: string;
	pageBuilder: Feature[];
	title: string;
	mainImage: MainImage;
}

// Generated by https://quicktype.io

export interface MainImage {
	_type: string;
	alt: string;
	asset: Asset;
}

export interface Asset {
	_createdAt: string;
	_id: string;
	_rev: string;
	_type: string;
	_updatedAt: string;
	assetId: string;
	extension: string;
	metadata: Metadata;
	mimeType: string;
	originalFilename: string;
	path: string;
	sha1hash: string;
	size: number;
	uploadId: string;
	url: string;
}

export interface Metadata {
	_type: string;
	blurHash: string;
	dimensions: Dimensions;
	hasAlpha: boolean;
	isOpaque: boolean;
	lqip: string;
	palette: Palette;
}

export interface Dimensions {
	_type: string;
	aspectRatio: number;
	height: number;
	width: number;
}

export interface Palette {
	_type: string;
	darkMuted: DarkMuted;
	darkVibrant: DarkMuted;
	dominant: DarkMuted;
	lightMuted: DarkMuted;
	lightVibrant: DarkMuted;
	muted: DarkMuted;
	vibrant: DarkMuted;
}

export interface DarkMuted {
	_type: string;
	background: string;
	foreground: string;
	population: number;
	title: string;
}

// Generated by https://quicktype.io
export interface Feature {
	_key: string;
	_type: string;
	features: FeatureItem[];
	heading: string;
	image: Image;
	tagline: string;
	title: string;
}

export interface Image {
	_type: string;
	alt: string;
	asset: SanityAsset;
}

export interface Asset {
	_ref: string;
	_type: string;
}

export interface FeatureItem {
	_key: string;
	_type: string;
	description: string;
	useIcon: boolean;
	useImage: boolean;
	icon: null | Icon;
	image: null | Image;
	link: null | string;
	title: string;
}
